config/routes.rb
MasterHunter::Application.routes.draw do
  scope module: :web do
    root to: "welcome#index"
    resources :users, only: [:create, :new]
    resources :welcome, only: [:index]
    resource :session, only: [:create, :destroy, :new]

    resources :posts, only: [:index, :show, :new, :create]
    resources :success_stories, only: [:index]

    namespace :admin do
      resources :posts, only: [:show, :index, :destroy, :edit, :update] do
        member do
          patch :publish
          patch :success
        end
      end
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  include PostRepository

  belongs_to :user

  validates :description, presence: true
  validates :place, presence: true
  validates :date, presence: true

  mount_uploader :photo, PostPhotoUploader

  state_machine :state, initial: :active do
    state :active
    state :deleted

    event :mark_as_deleted do
      transition active: :deleted
    end

    event :restore do
      transition deleted: :active
    end
  end

  state_machine :story_state, initial: :processed do
    state :processed
    state :success

    event :to_success do
      transition processed: :success
    end

    event :error_success do
      transition success: :processed
    end
  end

  state_machine :publication_state, initial: :unpublished do
    state :published
    state :unpublished

    event :publish do
      transition unpublished: :published
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password validations: false

  has_many :posts

  validates :email, email: true,
                    presence: true,
                    uniqueness: true

  validates :password_digest, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Concerns::AuthHelper

  protect_from_forgery with: :exception
  helper_method :signed_in?, :current_user
end

app/controllers/concerns/auth_helper.rb
module Concerns
  module AuthHelper
    def sign_in user
      session[:user_id] = user.id
    end

    def sign_out
      session[:user_id] = nil
    end

    def signed_in?
      !session[:user_id].nil?
    end

    def current_user
      if signed_in?
        User.find session[:user_id]
      else
        nil
      end
    end

    def authenticate_user!
      unless signed_in?
        redirect_to new_session_path
      end
    end

    def authenticate_admin!
      unless current_user && current_user.admin?
        redirect_to new_session_path
      end
    end
  end
end

app/controllers/web/admin/application_controller.rb
class Web::Admin::ApplicationController < Web::ApplicationController
  before_filter :authenticate_admin!
end

app/controllers/web/admin/posts_controller.rb
class Web::Admin::PostsController < ApplicationController
  def index
    @posts = Post.active
  end

  def show
    @post = Post.find params[:id]
  end

  def destroy
    @post = Post.find params[:id]
    @post.mark_as_deleted!

    redirect_to posts_path
  end

  def publish
    @post = Post.find params[:id]
    @post.publish

    redirect_to admin_posts_path
  end

  def edit
    @post = Post.find params[:id]
  end

  def update
    @post = Post.find params[:id]
    @post = @post.becomes PostEditType

    if @post.update params[:post]
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find params[:id]
    @post.mark_as_deleted
    redirect_to admin_posts_path
  end
end

app/controllers/web/application_controller.rb
class Web::ApplicationController < ApplicationController
end

app/controllers/web/posts_controller.rb
class Web::PostsController < Web::ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :destroy]

  def index
    @posts = Post.active.published
  end

  def new
    @post = PostEditType.new
  end

  def create
    @post = PostEditType.new params[:post]
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @post = Post.find params[:id]
  end
end

app/controllers/web/sessions_controller.rb
class Web::SessionsController < Web::ApplicationController
  def new
    @session = UserSignInType.new
  end

  def create
    @session = UserSignInType.new params[:user_sign_in_type]

    if @session.valid?
      sign_in @session.user
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/web/success_stories_controller.rb
class Web::SuccessStoriesController < ApplicationController
  def index
    @posts = Post.active.published.success
  end
end

app/controllers/web/users_controller.rb
class Web::UsersController < Web::ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = UserRegistrationType.new params[:user]

    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end
end

app/controllers/web/welcome_controller.rb
class Web::WelcomeController < Web::ApplicationController
  def index
    @posts = Post.last 10
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  include AutoHtml

  def map(place)
    auto_html place do
      google_map link_text: I18n.t(".view_map")
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.haml
.row.container
  .span2
    = image_tag "http://dl.dropboxusercontent.com/u/56984295/logo_color%20(1).png", class: :logo
  .span4
    %a{ href: "http://ulmic.ru" }
      %h4
        Молодёжный инициативный центр
      http://ulmic.ru

app/views/layouts/_menu.html.haml
.navbar-inverse{role: 'navigation'}
  .navbar-inner
    .container-fluid
      .navbar-header
        %button.navbar-toggle.collapsed{"type" => "button", 
          "data-toggle" => "collapse", "data-target" => "#navbar",
          "aria-expanded" => "false", "aria-controls" => "navbar"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{ href: root_path }
          Ищу хозяина
      .navbar-collapse.collapse{ "id" => "navbar"}
        %ul.nav.navbar-nav
          %li
            %a{ href: posts_path }
              Объявления
          %li
            %a{ href: success_stories_path }
              Истории успеха
          - if signed_in?
            %li
              %a{ href: new_post_path }
                Рассказать о бездомыше
            %li
              = link_to t('sign_out'), session_path, method: :delete
          - else
            %li
              %a{ href: new_session_path }
                Войти
            %li
              %a{ href: new_user_path }
                Регистрация
            %li
              %a{ href: new_user_path }
                Рассказать о бездомыше

app/views/layouts/application.html.haml
%head
  %title MasterHunter
  = stylesheet_link_tag    "bootstrap_and_overrides", media: "all"
  = stylesheet_link_tag    "application"
  = javascript_include_tag "application"
  = csrf_meta_tags

  %meta{"name" => "viewport", "content"=>"width=device-width", "initial-scale" => "1.0"}
%body
  = render 'layouts/menu'
  .container{class: 'col-lg-10 col-lg-offset-1'}
    = yield
  %hr
  = render 'layouts/footer'

app/views/layouts/cyborg.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "master_hunter"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "cyborg", :media => "all"
    = yield(:page_stylesheet) if content_for?(:page_stylesheet)


  %body

    = yield

    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "cyborg"
    = yield(:page_javascript) if content_for?(:page_javascript)

app/views/web/admin/posts/_form.html.haml
= simple_form_for @post, html: { class: 'form-horizontal' } do |f|
  = f.input :nickname
  = f.input :description
  = f.input :place
  = f.input :date
  = f.input :photo
  .form-actions
    = f.button :submit, class: 'btn btn-primary'
    = link_to t('.cancel', default: t("helpers.links.cancel")), posts_path, class: 'btn'

app/views/web/admin/posts/edit.html.haml
- model_class = Post
.page-header
  %h1=t '.title'
= render partial: "form"

app/views/web/admin/posts/index.html.haml
- model_class = Post
.page-header
  %h1=t '.title', default: model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %tbody
    - @posts.each do |post|
      %tr
        %td= link_to post.id, post_path(post)
        %td= post.nickname
        %td= post.description
        %td= post.place
        %td= post.date
        %td=l post.created_at
        - unless post.published?
          %td
            = link_to t('.publish'), publish_admin_post_path(post), method: :patch, class: 'btn btn-mini btn-primary'
        %td
          = link_to t('.destroy', default: t("helpers.links.destroy")), admin_post_path(post), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-mini btn-danger'

- if signed_in?
  = link_to t('.new', default: t("helpers.links.new")), new_post_path, class: 'btn btn-primary'
- else
  = link_to "sign in", new_session_path

app/views/web/admin/posts/show.html.haml
- model_class = Post
.page-header
  %h1=t '.title', default: model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:nickname) + ':'
  %br
  = @post.nickname
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @post.description
%p
  %strong= model_class.human_attribute_name(:place) + ':'
  %br
  = @post.place
%p
  %strong= model_class.human_attribute_name(:date) + ':'
  %br
  = @post.date

.form-actions
  = link_to t('.back', default: t("helpers.links.back")), posts_path, class: 'btn'
  = link_to t('.destroy', default: t("helpers.links.destroy")), post_path(@post), method: "delete", data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-danger'

app/views/web/posts/_form.html.haml
= stylesheet_link_tag :posts
= simple_form_for @post, html: { class: 'form-horizontal col-lg-6' } do |f|
  - f.with_options input_html: { class: 'form-control' } do |f|
    %fieldset
      .form-group
        = f.input :nickname 
      .form-group
        = f.input :description
      .form-group
        = f.input :place
      .form-group
        = f.input :date
      .form-group
        = f.input :photo
      = f.input :user_id, as: :hidden, input_html: { value: current_user.id }
    .form-actions
      = f.button :submit, class: 'btn btn-primary'
      = link_to t('cancel', default: t("helpers.links.cancel")), posts_path, class: 'btn'

app/views/web/posts/edit.html.haml
- model_class = Post
.page-header
  %h1=t '.title'
= render partial: "form"

app/views/web/posts/index.html.haml
= stylesheet_link_tag :posts
- model_class = Post
.page-header
  %h1=t '.title'
- if signed_in?
  = link_to t('.new', :default => t("helpers.links.new")), new_post_path, :class => 'btn btn-primary'
  %br
  %br
%table.table.table-hover
  %tbody
    - @posts.each do |post|
      %tr{ onclick: "return location.href = '#{post_path(post)}'"}
        %td
          %span.label.label-success
            = post.human_story_state_name
        %td
          %img{ src: post.photo.thumb }
        %td= link_to post.id, post_path(post)
        %td= post.nickname
        %td= post.description.first 50
        %td= post.place.first 50
        %td= post.date
        %td=l post.created_at

- if signed_in?
  = link_to t('.new', :default => t("helpers.links.new")), new_post_path, :class => 'btn btn-primary'
- else
  = link_to "sign in", new_session_path

app/views/web/posts/new.html.haml
- model_class = Post
.page-header
  %h1=t '.title'
= render partial: "form"

app/views/web/posts/show.html.haml
- model_class = Post
.page-header
  %h1=t '.title', default: model_class.model_name.human.titleize
%p
  %strong= model_class.human_attribute_name(:user) + ':'
  %br
  = @post.user.name

%p
  %strong= model_class.human_attribute_name(:nickname) + ':'
  %br
  = @post.nickname
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @post.description
%p
  %strong= model_class.human_attribute_name(:place) + ':'
  %br
  = @post.place
%p
  %strong= model_class.human_attribute_name(:date) + ':'
  %br
  = @post.date

.form-actions
  = link_to t('.back', default: t("helpers.links.back")), posts_path, class: 'btn'
  = link_to t('.destroy', default: t("helpers.links.destroy")), post_path(@post), method: "delete", data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-danger'

app/views/web/success_stories/index.html.haml
- @posts.each do |post|
  .row
    .span3
      %img{ src: post.photo.thumb, class: 'img-polaroid' }
    .span4
      %h2= post.nickname
      = post.description
      %a{ href: post.user }
  %hr

app/views/web/users/_form.html.haml
= simple_form_for @user, html: { class: 'form-horizontal' } do |f|
  = f.input :name
  = f.input :email
  = f.input :password
  = f.input :phone
  .form-actions
    = f.button :submit, t('save'), class: 'btn btn-primary'
    = link_to t('cancel'), users_path, class: 'btn'

app/views/web/users/new.html.haml
- model_class = User
.page-header
  %h1=t '.title'
= render partial: "form"

app/views/web/welcome/index.html.haml
- @posts.each do |post|
  .row
    .span3
      %img{ src: post.photo, class: 'img-polaroid' }
    .span4
      %h2= post.nickname
      = post.description
  %hr